### ISSUE TITLE
2.2节transformer

### ISSUE THREAD

**Issue by yj8023xx** [datawhalechina/learn-nlp-with-transformers#12]
解码器部分最后key矩阵和value矩阵应该来自编码器最后的输出吧

**Comment by erenup** [comment]
编码器一般有多层，第一个编码器的输入是一个序列，最后一个编码器输出是一组注意力向量 K 和 V。这些注意力向量将会输入到每个解码器的Encoder-Decoder Attention层，这有助于解码器把注意力集中中输入序列的合适位置。

这句话吗？还是哪一句话呢？谢谢。

**Comment by yj8023xx** [comment]
“Encoder-Decoder Attention层的原理和多头注意力（multiheaded Self Attention）机制类似，不同之处是：Encoder-Decoder Attention层是使用前一层的输出来构造 Query 矩阵，而 Key 矩阵和 Value 矩阵来自于**解码器**最终的输出“

是以上这句

**Comment by erenup** [comment]
已修改。感谢。

**Comment by yj8023xx** [comment]
不客气
