### ISSUE TITLE
about （可能是我的版本问题） 4.5-生成任务-语言模型

### ISSUE THREAD

**Issue by yuanyihan** [datawhalechina/learn-nlp-with-transformers#24]
这个里面有一段：
```python
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_datasets["train"][:1000],
    eval_dataset=lm_datasets["validation"][:100],
    data_collator=data_collator,
)
```
**可能是我的版本问题，datasets切片之后类型是dict，好像不能直接赋值给dataset，这样会报错：**
```
***** Running training *****
  Num examples = 3
  Num Epochs = 1
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 1
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-113-3435b262f1ae> in <module>()
----> 1 trainer.train()

4 frames
/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

KeyError: 2
```
因为切片之后，len就不是样本长度，而是dict的K的数量（3个）

原始数据：
`Dataset({
    features: ['attention_mask', 'input_ids', 'labels'],
    num_rows: 19240
})`
切片之后dict：
`Type:        dict
String form: {'attention_mask': [[1, 1,。。。。。。后面太长了`
其实应该要的是
`Dataset({
    features: ['attention_mask', 'input_ids', 'labels'],
    num_rows:1000
})`
==================这边的我的参考代码===========
```python
from datasets import Dataset
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=Dataset.from_dict(lm_datasets["train"][:1000]),
    。。。。
```
=======因为可能是版本问题，我这边给出一些版本说明=====
datasets-1.11.0 fsspec-2021.7.0 huggingface-hub-0.0.12 pyyaml-5.4.1 sacremoses-0.0.45 tokenizers-0.10.3 transformers-4.9.2 xxhash-2.0.2 
Pytorch版本：1.9.0+cu102

**Comment by yuanyihan** [comment]
datasets-1.6.2 fsspec-2021.7.0 huggingface-hub-0.0.16 sacremoses-0.0.45 tokenizers-0.10.3 tqdm-4.49.0 transformers-4.4.2 xxhash-2.0.2
Pytorch版本：1.9.0+cu102
测试结果：报错：
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-3435b262f1ae> in <module>()
----> 1 trainer.train()

4 frames
/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

KeyError: 1
```
===其中切片类型===
```
Type:        dict
String form: {'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 <...>  764, 15945, 2488, 12, 31, 3303, 3835, 547, 11544, 772, 287, 262, 4165, 4266, 764, 15945, 7799]]}
Length:      3
Docstring:  
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)
```

**Comment by erenup** [comment]
应该是版本问题，我记得之前测试过。我来看看哪个版本对应上这份代码的。

**Comment by HHUYuYang** [comment]
> 这个里面有一段：
> 
> ```python
> trainer = Trainer(
>     model=model,
>     args=training_args,
>     train_dataset=lm_datasets["train"][:1000],
>     eval_dataset=lm_datasets["validation"][:100],
>     data_collator=data_collator,
> )
> ```
> 
> **可能是我的版本问题，datasets切片之后类型是dict，好像不能直接赋值给dataset，这样会报错：**
> 
> ```
> ***** Running training *****
>   Num examples = 3
>   Num Epochs = 1
>   Instantaneous batch size per device = 8
>   Total train batch size (w. parallel, distributed & accumulation) = 8
>   Gradient Accumulation steps = 1
>   Total optimization steps = 1
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-113-3435b262f1ae> in <module>()
> ----> 1 trainer.train()
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
>      42     def fetch(self, possibly_batched_index):
>      43         if self.auto_collation:
> ---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
>      45         else:
>      46             data = self.dataset[possibly_batched_index]
> 
> KeyError: 2
> ```
> 
> 因为切片之后，len就不是样本长度，而是dict的K的数量（3个）
> 
> 原始数据：
> `Dataset({ features: ['attention_mask', 'input_ids', 'labels'], num_rows: 19240 })`
> 切片之后dict：
> `Type: dict String form: {'attention_mask': [[1, 1,。。。。。。后面太长了`
> 其实应该要的是
> `Dataset({ features: ['attention_mask', 'input_ids', 'labels'], num_rows:1000 })`
> ==================这边的我的参考代码===========
> 
> ```python
> from datasets import Dataset
> trainer = Trainer(
>     model=model,
>     args=training_args,
>     train_dataset=Dataset.from_dict(lm_datasets["train"][:1000]),
>     。。。。
> ```
> 
> =======因为可能是版本问题，我这边给出一些版本说明=====
> datasets-1.11.0 fsspec-2021.7.0 huggingface-hub-0.0.12 pyyaml-5.4.1 sacremoses-0.0.45 tokenizers-0.10.3 transformers-4.9.2 xxhash-2.0.2
> Pytorch版本：1.9.0+cu102

nice.

**Comment by yuanyihan** [comment]
你们是不是有个技术交流群？群里没有说这个的么？

**Comment by HHUYuYang** [comment]
> 你们是不是有个技术交流群？群里没有说这个的么？
目前只在这里看到了解答

**Comment by yuanyihan** [comment]
> > 你们是不是有个技术交流群？群里没有说这个的么？
> > 目前只在这里看到了解答

我。。。。。我。。。我自己看这个项目的，，，之前有人在一个技术群讨论这个项目，，所以，顺便看了一下。。。
我是不认识他们的，，好像交流群据说满了，也进不去。。。就，，，就很迷~

**Comment by erenup** [comment]
有一个读者群，你可以加一下bit_pku_eecs 他拉你。这个issue的问题，我们当时调试这个jupyter的同学正在看。

**Comment by yuanyihan** [comment]
之前加了，那个多多，，但是好像一直没通过

/*****以下内容是邮件签名自动添加*****/ 
/*****MY_EMAIL_T——邮件尾文件说明开始*****/
#ifndef&nbsp;__MY_EMAIL_T__
#define&nbsp;__MY_EMAIL_T__
#define&nbsp;&nbsp;姓名 &nbsp; &nbsp;"袁一涵" &nbsp;&nbsp;//姓名为袁一涵 
#define&nbsp;&nbsp;QQ号 &nbsp; &nbsp;1226317595&nbsp;//QQ号为1226317595
#define&nbsp;手机号 &nbsp;18192015917&nbsp;//手机号为18192015917
#define&nbsp;E-mail ***@***.***&nbsp;//email
#endif
/*****MY_EMAIL_T——邮件尾文件说明结束*****/
/*********** (C) COPYRIGHT @Yuan Yihan *****END OF FILE****/



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "datawhalechina/learn-nlp-with-transformers"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Sep 1, 2021 08:35 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [datawhalechina/learn-nlp-with-transformers] about （可能是我的版本问题） 4.5-生成任务-语言模型 (#24)





 
有一个读者群，你可以加一下bit_pku_eecs 他拉你。这个issue的问题，我们当时调试这个jupyter的同学正在看。

**Comment by caijie12138** [comment]
就是[:1000]部分的问题，运行时需要将“[:1000]”删除。但是删除之后如果在jupyter笔记本里运行train(),会导致jupyter笔记本崩掉，所以建议还是在本地运行比较好。

**Comment by caijie12138** [comment]
> 这个里面有一段：
> 
> ```python
> trainer = Trainer(
>     model=model,
>     args=training_args,
>     train_dataset=lm_datasets["train"][:1000],
>     eval_dataset=lm_datasets["validation"][:100],
>     data_collator=data_collator,
> )
> ```
> 
> **可能是我的版本问题，datasets切片之后类型是dict，好像不能直接赋值给dataset，这样会报错：**
> 
> ```
> ***** Running training *****
>   Num examples = 3
>   Num Epochs = 1
>   Instantaneous batch size per device = 8
>   Total train batch size (w. parallel, distributed & accumulation) = 8
>   Gradient Accumulation steps = 1
>   Total optimization steps = 1
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-113-3435b262f1ae> in <module>()
> ----> 1 trainer.train()
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
>      42     def fetch(self, possibly_batched_index):
>      43         if self.auto_collation:
> ---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
>      45         else:
>      46             data = self.dataset[possibly_batched_index]
> 
> KeyError: 2
> ```
> 
> 因为切片之后，len就不是样本长度，而是dict的K的数量（3个）
> 
> 原始数据：
> `Dataset({ features: ['attention_mask', 'input_ids', 'labels'], num_rows: 19240 })`
> 切片之后dict：
> `Type: dict String form: {'attention_mask': [[1, 1,。。。。。。后面太长了`
> 其实应该要的是
> `Dataset({ features: ['attention_mask', 'input_ids', 'labels'], num_rows:1000 })`
> ==================这边的我的参考代码===========
> 
> ```python
> from datasets import Dataset
> trainer = Trainer(
>     model=model,
>     args=training_args,
>     train_dataset=Dataset.from_dict(lm_datasets["train"][:1000]),
>     。。。。
> ```
> 
> =======因为可能是版本问题，我这边给出一些版本说明=====
> datasets-1.11.0 fsspec-2021.7.0 huggingface-hub-0.0.12 pyyaml-5.4.1 sacremoses-0.0.45 tokenizers-0.10.3 transformers-4.9.2 xxhash-2.0.2
> Pytorch版本：1.9.0+cu102

将“[:1000]”删除，在本地运行即可。

**Comment by erenup** [comment]
已经 解决
